stages:
  - build

variables:
  CI_NODE_INDEX: "1"

cache:
  paths:
    - node_modules/

job:
  image: node:14
  stage: build
  script:
    - npm install
    - npm run build
    - mv .next public
  artifacts:
    paths:
      - public
  only:
    - main