# The Docker image that will be used to build your app
image: node:14
# Functions that should be executed before the build script is run
before_script:
  - npm install
pages:
  script:
    - npm run build
    - rm -r public/*
    - mv out/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  only:
    #Trigger a new build and deploy only when there is a push to main
    - main
